/*
 * Copyright (c) 2022, Rodolfo Ruiz-Velasco <https://github.com/lequietriot>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package rs.musicmask;

import java.util.HashMap;

public final class MusicTrackMapping {

    public final HashMap<String, Integer> musicTracks = new HashMap<>();

    MusicTrackMapping() {
        musicTracks.put("Login Screen", 0);

        musicTracks.put("Iban", 1);
        musicTracks.put("Moody", 10);
        musicTracks.put("Beyond", 100);
        musicTracks.put("Gnome Village 2", 101);
        musicTracks.put("Alone", 102);
        musicTracks.put("Oriental", 103);
        musicTracks.put("Camelot", 104);
        musicTracks.put("Tomorrow", 105);
        musicTracks.put("Expanse", 106);
        musicTracks.put("Miles Away", 107);
        musicTracks.put("Starlight", 108);
        musicTracks.put("Theme", 109);
        musicTracks.put("Spooky 2", 11);
        musicTracks.put("Serenade", 110);
        musicTracks.put("Still Night", 111);
        musicTracks.put("Gnomeball", 112);
        musicTracks.put("Lightness", 113);
        musicTracks.put("Jungly 1", 114);
        musicTracks.put("Jungly 2", 115);
        musicTracks.put("Greatness", 116);
        musicTracks.put("Jungly 3", 117);
        musicTracks.put("Faerie", 118);
        musicTracks.put("Fishing", 119);
        musicTracks.put("Long Way Home", 12);
        musicTracks.put("Shining", 120);
        musicTracks.put("Forbidden", 121);
        musicTracks.put("Shine", 122);
        musicTracks.put("Arabian 2", 123);
        musicTracks.put("Arabian 3", 124);
        musicTracks.put("Garden", 125);
        musicTracks.put("We are the Fairies", 126);
        musicTracks.put("Nightfall", 127);
        musicTracks.put("Grumpy", 128);
        musicTracks.put("Spooky Jungle", 129);
        musicTracks.put("Mage Arena", 13);
        musicTracks.put("Tree Spirits", 130);
        musicTracks.put("Understanding", 131);
        musicTracks.put("Breeze", 132);
        musicTracks.put("The Tower", 133);
        musicTracks.put("La Mort", 134);
        musicTracks.put("Ambience 2 (Old)", 135);
        musicTracks.put("Jaws of the Basilisk", 135);
        musicTracks.put("Ambience 3 (Old)", 136);
        musicTracks.put("Lair of the Basilisk", 136);
        musicTracks.put("Ambience 4 (Old)", 137);
        musicTracks.put("The Jormungand defeated! (Unlisted)", 137);
        musicTracks.put("Emperor", 138);
        musicTracks.put("Ballad of the Basilisk", 139);
        musicTracks.put("fade test (Old Sound System Test)", 139);
        musicTracks.put("Witching", 14);
        musicTracks.put("Talking Forest", 140);
        musicTracks.put("Barbarianism", 141);
        musicTracks.put("Complication", 142);
        musicTracks.put("Down to Earth", 143);
        musicTracks.put("Scape Cave", 144);
        musicTracks.put("Yesteryear", 145);
        musicTracks.put("Zealot", 146);
        musicTracks.put("silence (Sound System Test)", 147);
        musicTracks.put("Emotion", 148);
        musicTracks.put("Principality", 149);
        musicTracks.put("Workshop", 15);
        musicTracks.put("Mouse Trap", 150);
        musicTracks.put("Start", 151);
        musicTracks.put("Ballad of Enchantment", 152);
        musicTracks.put("Expedition", 153);
        musicTracks.put("Bone Dance", 154);
        musicTracks.put("Neverland", 155);
        musicTracks.put("Mausoleum", 156);
        musicTracks.put("Medieval", 157);
        musicTracks.put("Quest", 158);
        musicTracks.put("Gaol", 159);
        musicTracks.put("Scape Main", 16);
        musicTracks.put("Army of Darkness", 160);
        musicTracks.put("Long Ago", 161);
        musicTracks.put("Tribal Background", 162);
        musicTracks.put("Flute Salad", 163);
        musicTracks.put("Landlubber", 164);
        musicTracks.put("Tribal", 165);
        musicTracks.put("Fanfare 2", 166);
        musicTracks.put("Fanfare 3", 167);
        musicTracks.put("Lonesome", 168);
        musicTracks.put("Crystal Sword", 169);
        musicTracks.put("Escape", 17);
        musicTracks.put("The Shadow", 170);
        musicTracks.put("null (Sound System Test)", 171);
        musicTracks.put("Jungle Island", 172);
        musicTracks.put("Dunjun", 173);
        musicTracks.put("Desert Voyage", 174);
        musicTracks.put("Spirit", 175);
        musicTracks.put("Undercurrent", 176);
        musicTracks.put("Adventure", 177);
        musicTracks.put("Courage", 178);
        musicTracks.put("Underground", 179);
        musicTracks.put("Horizon", 18);
        musicTracks.put("Attention", 180);
        musicTracks.put("Crystal Cave", 181);
        musicTracks.put("Dangerous", 182);
        musicTracks.put("Troubled", 183);
        musicTracks.put("Magical Journey", 184);
        musicTracks.put("Magic Dance", 185);
        musicTracks.put("Arrival", 186);
        musicTracks.put("Tremble", 187);
        musicTracks.put("In the Manor", 188);
        musicTracks.put("Wolf Mountain", 189);
        musicTracks.put("Arabique", 19);
        musicTracks.put("Heart and Mind", 190);
        musicTracks.put("Knightly", 191);
        musicTracks.put("Trinity", 192);
        musicTracks.put("Mellow", 193);
        musicTracks.put("Brimstail's Scales", 194);
        musicTracks.put("Delrith's Theme (Unlisted)", 195);
        musicTracks.put("Wally's Theme (Unlisted)", 196);
        musicTracks.put("Lament of Meiyerditch", 197);
        musicTracks.put("Dagannoth Dawn", 198);
        musicTracks.put("Reign of the Basilisk", 199);
        musicTracks.put("Sea Slug Sailing Journey (Unlisted, Old)", 199);
        musicTracks.put("Autumn Voyage", 2);
        musicTracks.put("Lullaby", 20);
        musicTracks.put("The Mollusc Menace", 200);
        musicTracks.put("Slug a Bug Ball", 201);
        musicTracks.put("Prime Time", 202);
        musicTracks.put("My Arm's Journey", 203);
        musicTracks.put("Roc and Roll", 204);
        musicTracks.put("High Spirits", 205);
        musicTracks.put("Floating Free", 206);
        musicTracks.put("Scape Hunter", 207);
        musicTracks.put("Jungle Island XMAS", 208);
        musicTracks.put("Jungle Bells", 209);
        musicTracks.put("Monarch Waltz", 21);
        musicTracks.put("Sea Shanty XMAS", 210);
        musicTracks.put("Pirates of Penance", 211);
        musicTracks.put("Barbarian Assault Tutorial (Unlisted)", 212);
        musicTracks.put("Labyrinth", 213);
        musicTracks.put("Undead Dungeon", 214);
        musicTracks.put("Tarn Razorlor Fight (Unlisted)", 215);
        musicTracks.put("Espionage", 216);
        musicTracks.put("Have an Ice Day", 217);
        musicTracks.put("Penguin Performance (Unlisted)", 218);
        musicTracks.put("Cold War (Unlisted Cutscene)", 219);
        musicTracks.put("Gnome King", 22);
        musicTracks.put("Island of the Trolls", 220);
        musicTracks.put("Jester Minute", 221);
        musicTracks.put("Major Miner", 222);
        musicTracks.put("Norse Code", 223);
        musicTracks.put("Ogre the Top", 224);
        musicTracks.put("Volcanic Vikings", 225);
        musicTracks.put("The Fremennik Isles Ice Troll Caves (Unlisted)", 226);
        musicTracks.put("The Fremennik Isles Angry King (Unlisted)", 227);
        musicTracks.put("Garden of Autumn", 228);
        musicTracks.put("Garden of Spring", 229);
        musicTracks.put("Fe Fi Fo Fum", 23);
        musicTracks.put("Garden of Summer", 230);
        musicTracks.put("Garden of Winter", 231);
        musicTracks.put("Sorceress's Garden Centre (Unlisted)", 232);
        musicTracks.put("The General's Shadow The Ghost of Bouncer (Unlisted)", 233);
        musicTracks.put("Creature Cruelty", 234);
        musicTracks.put("Magic, Magic, Magic", 235);
        musicTracks.put("Mutant Medley", 236);
        musicTracks.put("Work, Work, Work", 237);
        musicTracks.put("Zombiism", 238);
        musicTracks.put("Brain Battle (Unused)", 239);
        musicTracks.put("Attack 1", 24);
        musicTracks.put("Dorgeshuun City", 240);
        musicTracks.put("Stagnant", 241);
        musicTracks.put("Time Out", 242);
        musicTracks.put("Stratosphere", 243);
        musicTracks.put("Waterlogged", 244);
        musicTracks.put("Natural", 245);
        musicTracks.put("Grotto", 246);
        musicTracks.put("Artistry", 247);
        musicTracks.put("Aztec", 248);
        musicTracks.put("Dorgeshuun Deep", 249);
        musicTracks.put("Attack 2", 25);
        musicTracks.put("Surok's Revenge (Unlisted)", 250);
        musicTracks.put("Forest", 251);
        musicTracks.put("Elven Mist", 252);
        musicTracks.put("Lost Soul", 253);
        musicTracks.put("Meridian", 254);
        musicTracks.put("Woodland", 255);
        musicTracks.put("Overpass", 256);
        musicTracks.put("Sojourn", 257);
        musicTracks.put("Contest", 258);
        musicTracks.put("Crystal Castle", 259);
        musicTracks.put("Attack 3", 26);
        musicTracks.put("Insect Queen", 260);
        musicTracks.put("Marzipan", 261);
        musicTracks.put("Righteousness", 262);
        musicTracks.put("Bandit Camp", 263);
        musicTracks.put("Mad Eadgar", 264);
        musicTracks.put("Superstition", 265);
        musicTracks.put("Bone Dry", 266);
        musicTracks.put("Sunburn", 267);
        musicTracks.put("Everywhere", 268);
        musicTracks.put("Competition", 269);
        musicTracks.put("Attack 4", 27);
        musicTracks.put("Exposed", 270);
        musicTracks.put("Well of Voyage", 271);
        musicTracks.put("Alternative Root", 272);
        musicTracks.put("Easter Jig", 273);
        musicTracks.put("Rising Damp", 274);
        musicTracks.put("Slice of Station", 275);
        musicTracks.put("H.A.M. and Seek", 276);
        musicTracks.put("Haunted Mine", 277);
        musicTracks.put("Deep Down", 278);
        musicTracks.put("H.A.M. Attack", 279);
        musicTracks.put("Attack 5", 28);
        musicTracks.put("Another Slice of H.A.M. Grand Opening (Unlisted)", 280);
        musicTracks.put("Slice of Silent Movie", 281);
        musicTracks.put("Chamber", 282);
        musicTracks.put("Everlasting", 283);
        musicTracks.put("Misellania", 284);
        musicTracks.put("Etceteria", 285);
        musicTracks.put("Shadowland", 286);
        musicTracks.put("Lair", 287);
        musicTracks.put("Deadlands", 288);
        musicTracks.put("Rellekka", 289);
        musicTracks.put("Attack 6", 29);
        musicTracks.put("Saga", 290);
        musicTracks.put("Borderland", 291);
        musicTracks.put("Stranded", 292);
        musicTracks.put("Legend", 293);
        musicTracks.put("Frostbite", 294);
        musicTracks.put("Warrior", 295);
        musicTracks.put("Technology", 296);
        musicTracks.put("Etcetera Anthem (Unlisted)", 297);
        musicTracks.put("Illusive", 298);
        musicTracks.put("Inadequacy", 299);
        musicTracks.put("Unknown Land", 3);
        musicTracks.put("Voodoo Cult", 30);
        musicTracks.put("Untouchable", 300);
        musicTracks.put("Down and Out", 301);
        musicTracks.put("On the Up", 302);
        musicTracks.put("Monkey Madness", 303);
        musicTracks.put("Marooned", 304);
        musicTracks.put("Anywhere", 305);
        musicTracks.put("Island Life", 306);
        musicTracks.put("Temple", 307);
        musicTracks.put("Suspicious", 308);
        musicTracks.put("Looking Back", 309);
        musicTracks.put("Fight of the Basilisk", 31);
        musicTracks.put("Game Intro 1 (Unlisted, Old)", 31);
        musicTracks.put("Dwarf Theme", 310);
        musicTracks.put("Showdown", 311);
        musicTracks.put("Find My Way", 312);
        musicTracks.put("Goblin Village", 313);
        musicTracks.put("Castle Wars", 314);
        musicTracks.put("Crop Circles (Unlisted)", 315);
        musicTracks.put("The Navigator", 316);
        musicTracks.put("Melodrama", 317);
        musicTracks.put("Ready for Battle", 318);
        musicTracks.put("Stillness", 319);
        musicTracks.put("Voyage", 32);
        musicTracks.put("Lighthouse", 320);
        musicTracks.put("Scape Scared", 321);
        musicTracks.put("Out of the Deep", 322);
        musicTracks.put("Underground Pass", 323);
        musicTracks.put("Background", 324);
        musicTracks.put("Cave Background", 325);
        musicTracks.put("Dark", 326);
        musicTracks.put("Dream", 327);
        musicTracks.put("March", 328);
        musicTracks.put("Regal", 329);
        musicTracks.put("Gnome Village", 33);
        musicTracks.put("Cellar Song", 330);
        musicTracks.put("Scape Sad", 331);
        musicTracks.put("Scape Wild", 332);
        musicTracks.put("Spooky", 333);
        musicTracks.put("Pirates of Peril", 334);
        musicTracks.put("Romancing the Crone", 335);
        musicTracks.put("Dangerous Road", 336);
        musicTracks.put("Faithless", 337);
        musicTracks.put("Tiptoe", 338);
        musicTracks.put("The Terrible Tower", 339);
        musicTracks.put("Wonder", 34);
        musicTracks.put("Masquerade", 340);
        musicTracks.put("The Slayer", 341);
        musicTracks.put("Body Parts", 342);
        musicTracks.put("Monster Melee", 343);
        musicTracks.put("Fenkenstrain's Refrain", 344);
        musicTracks.put("Barking Mad", 345);
        musicTracks.put("Goblin Game", 346);
        musicTracks.put("Fruits de Mer", 347);
        musicTracks.put("Narnode's Theme", 348);
        musicTracks.put("Impetuous", 349);
        musicTracks.put("Sea Shanty 2", 35);
        musicTracks.put("Sailing (Full)", 350);
        musicTracks.put("Dynasty", 351);
        musicTracks.put("Scarab", 352);
        musicTracks.put("Shipwrecked", 353);
        musicTracks.put("Phasmatys", 354);
        musicTracks.put("The Other Side", 355);
        musicTracks.put("Settlement", 356);
        musicTracks.put("Cave of Beasts", 357);
        musicTracks.put("Dragontooth Island", 358);
        musicTracks.put("Sarcophagus", 359);
        musicTracks.put("Arabian", 36);
        musicTracks.put("Dragon Slayer Elvarg Attacks Lady Lumbridge!", 360);
        musicTracks.put("Down Below", 361);
        musicTracks.put("Karamja Jam", 362);
        musicTracks.put("7th Realm", 363);
        musicTracks.put("Pathways", 364);
        musicTracks.put("The Maze", 365);
        musicTracks.put("Eagle Peak", 366);
        musicTracks.put("Barb Wire", 367);
        musicTracks.put("Observatory Quest Fixing the Telescope", 368);
        musicTracks.put("Time to Mine", 369);
        musicTracks.put("Deep Wildy", 37);
        musicTracks.put("In Between", 370);
        musicTracks.put("School's Out", 371);
        musicTracks.put("Far Away", 372);
        musicTracks.put("Claustrophobia", 373);
        musicTracks.put("Knightmare", 374);
        musicTracks.put("Fight or Flight", 375);
        musicTracks.put("Temple of Light", 376);
        musicTracks.put("The Golem", 377);
        musicTracks.put("Forgotten", 378);
        musicTracks.put("Throne of the Demon", 379);
        musicTracks.put("Trawler", 38);
        musicTracks.put("Dance of the Undead", 380);
        musicTracks.put("Dangerous Way", 381);
        musicTracks.put("Lore and Order", 382);
        musicTracks.put("City of the Dead", 383);
        musicTracks.put("Hypnotized", 384);
        musicTracks.put("King's Ransom Treacherous Siblings", 385);
        musicTracks.put("Too Many Cooks...", 386);
        musicTracks.put("Sphinx", 387);
        musicTracks.put("Mirage", 388);
        musicTracks.put("Cave of the Goblins", 389);
        musicTracks.put("Church Organ 1 (Unlisted)", 39);
        musicTracks.put("Romper Chomper", 390);
        musicTracks.put("Strength of Saradomin", 391);
        musicTracks.put("Zogre Dance", 392);
        musicTracks.put("Path of Peril", 393);
        musicTracks.put("Wayward", 394);
        musicTracks.put("Tale of Keldagrim", 395);
        musicTracks.put("Land of the Dwarves", 396);
        musicTracks.put("Tears of Guthix", 397);
        musicTracks.put("The Power of Tears", 398);
        musicTracks.put("Zamorak Zoo", 399);
        musicTracks.put("Hells Bells", 4);
        musicTracks.put("Church Organ 2 (Unlisted)", 40);
        musicTracks.put("Scape Original", 400);
        musicTracks.put("The Adventurer (Unlisted)", 401);
        musicTracks.put("The Rouges' Den", 402);
        musicTracks.put("The Far Side", 403);
        musicTracks.put("Armageddon", 404);
        musicTracks.put("The Giant Dwarf The Consortium", 405);
        musicTracks.put("The Giant Dwarf Boat Ride to Keldagrim", 406);
        musicTracks.put("The Lost Melody", 407);
        musicTracks.put("Bandos Battalion", 408);
        musicTracks.put("Frogland", 409);
        musicTracks.put("Expecting", 41);
        musicTracks.put("The Lost Tribe Peace Treaty (Cutscene)", 410);
        musicTracks.put("Evil Bob's Island", 411);
        musicTracks.put("Into the Abyss", 412);
        musicTracks.put("The Quiz Master", 413);
        musicTracks.put("Armadyl Alliance", 414);
        musicTracks.put("Athlete's Foot (Unused)", 415);
        musicTracks.put("Gnome Village Party", 416);
        musicTracks.put("Beneath the Stronghold", 417);
        musicTracks.put("Corporal Punishment", 418);
        musicTracks.put("Pheasant Peasant", 419);
        musicTracks.put("Wilderness 2", 42);
        musicTracks.put("The Lost Tribe", 420);
        musicTracks.put("Troubled Waters", 421);
        musicTracks.put("Nether Realm", 422);
        musicTracks.put("Scorpia Dances", 423);
        musicTracks.put("Devils May Care", 424);
        musicTracks.put("The Chosen", 425);
        musicTracks.put("Pick & Shovel", 426);
        musicTracks.put("Warpath", 427);
        musicTracks.put("Clan Wars (Unused)", 428);
        musicTracks.put("Clan Wars", 428);
        musicTracks.put("Shining Spirit", 429);
        musicTracks.put("Wilderness 3", 43);
        musicTracks.put("Bane", 430);
        musicTracks.put("Grimly Fiendish", 431);
        musicTracks.put("Coil", 432);
        musicTracks.put("Thrall of the Serpent", 433);
        musicTracks.put("Have a Blast", 434);
        musicTracks.put("Wilderness", 435);
        musicTracks.put("Forgettable Melody", 436);
        musicTracks.put("Bunny's Sugar Rush", 437);
        musicTracks.put("Drunken Dwarf (Unlisted Cutscene)", 438);
        musicTracks.put("Maws, Jaws & Claws", 439);
        musicTracks.put("Right on Track", 44);
        musicTracks.put("That Sullen Hall", 440);
        musicTracks.put("Invader", 441);
        musicTracks.put("Dies Irae", 442);
        musicTracks.put("Nox Irae", 443);
        musicTracks.put("Soul Fall", 444);
        musicTracks.put("Rugged Terrain", 445);
        musicTracks.put("Dwarven Domain", 446);
        musicTracks.put("Over to Nardah", 447);
        musicTracks.put("The Monsters Below", 448);
        musicTracks.put("The Militia", 449);
        musicTracks.put("Venture 2", 45);
        musicTracks.put("Down by the Docks", 450);
        musicTracks.put("Kourend the Magnificent", 451);
        musicTracks.put("The Forlorn Homestead", 452);
        musicTracks.put("Jungle Hunt", 453);
        musicTracks.put("Home Sweet Home", 454);
        musicTracks.put("Arcane", 455);
        musicTracks.put("Country Jig", 456);
        musicTracks.put("Monkey Trouble", 457);
        musicTracks.put("Scape Ape", 458);
        musicTracks.put("Monkey Sadness", 459);
        musicTracks.put("Harmony 2", 46);
        musicTracks.put("Joy of the Hunt", 460);
        musicTracks.put("The Desolate Isle", 461);
        musicTracks.put("Spirits of the Elid", 462);
        musicTracks.put("Fire and Brimstone", 463);
        musicTracks.put("The Genie", 464);
        musicTracks.put("Desert Heat", 465);
        musicTracks.put("Scape Ground", 466);
        musicTracks.put("Monkey Business", 467);
        musicTracks.put("Monkey Badness", 468);
        musicTracks.put("In the Pits", 469);
        musicTracks.put("Duel Arena", 47);
        musicTracks.put("Strange Place", 470);
        musicTracks.put("Brew Hoo Hoo", 471);
        musicTracks.put("Darkly Altared", 472);
        musicTracks.put("Massacre (Unused)", 472);
        musicTracks.put("TzHaar!", 473);
        musicTracks.put("Last Man Standing", 474);
        musicTracks.put("Wild Side", 475);
        musicTracks.put("Dead Can Dance", 476);
        musicTracks.put("The Doors of Dinh", 477);
        musicTracks.put("The Cellar Dwellers", 478);
        musicTracks.put("Jungle Troubles", 479);
        musicTracks.put("Morytania", 48);
        musicTracks.put("Mined Out (Unlisted)", 480);
        musicTracks.put("Catch Me If You Can", 481);
        musicTracks.put("Rat a Tat Tat", 482);
        musicTracks.put("Ice and Fire", 483);
        musicTracks.put("Tail of Two Cats Bob and Neite (Unlisted)", 484);
        musicTracks.put("The Noble Rodent", 485);
        musicTracks.put("Altar Ego", 486);
        musicTracks.put("Lower Depths", 487);
        musicTracks.put("March of the Shayzien", 488);
        musicTracks.put("Bubble and Squeak", 489);
        musicTracks.put("Wander", 49);
        musicTracks.put("Sarim's Vermin", 490);
        musicTracks.put("Rat Hunt", 491);
        musicTracks.put("Upper Depths", 492);
        musicTracks.put("Fire in the Deep", 493);
        musicTracks.put("Ascent", 494);
        musicTracks.put("The Desolate Mage", 495);
        musicTracks.put("The Trade Parade (Unlisted)", 496);
        musicTracks.put("The Trade Parade", 496);
        musicTracks.put("Aye Car Rum Ba", 497);
        musicTracks.put("Blistering Barnacles", 498);
        musicTracks.put("Darkness in the Depths", 499);
        musicTracks.put("Sad Meadow", 5);
        musicTracks.put("Al Kharid", 50);
        musicTracks.put("Inferno", 500);
        musicTracks.put("Distant Land (Old)", 501);
        musicTracks.put("Distant Land", 501);
        musicTracks.put("Mor Ul Rek", 502);
        musicTracks.put("Lagoon", 503);
        musicTracks.put("Fangs for the Memory", 504);
        musicTracks.put("Pharaoh's Tomb", 505);
        musicTracks.put("Land Down Under", 506);
        musicTracks.put("Lava is Mine", 507);
        musicTracks.put("Meddling Kids", 508);
        musicTracks.put("Corridors of Power", 509);
        musicTracks.put("Trawler Minor", 51);
        musicTracks.put("Slither and Tither", 510);
        musicTracks.put("In the Clink", 511);
        musicTracks.put("Preservation", 512);
        musicTracks.put("Preserved", 513);
        musicTracks.put("Fossilised", 514);
        musicTracks.put("Mudskipper Melody", 515);
        musicTracks.put("Preserved & Preservation Merged (Unlisted)", 516);
        musicTracks.put("Subterranea", 517);
        musicTracks.put("Tempest", 518);
        musicTracks.put("Incantation", 519);
        musicTracks.put("Serene", 52);
        musicTracks.put("Grip of the Talon", 520);
        musicTracks.put("Revenants", 521);
        musicTracks.put("On the Shore", 522);
        musicTracks.put("Land of Snow", 523);
        musicTracks.put("Xenophobe", 524);
        musicTracks.put("Title Fight", 525);
        musicTracks.put("Winter Funfair", 526);
        musicTracks.put("The Forsaken", 527);
        musicTracks.put("Victory is Mine", 528);
        musicTracks.put("Woe of the Wyvern", 529);
        musicTracks.put("Royale", 53);
        musicTracks.put("In the Brine", 530);
        musicTracks.put("Lucid Nightmare", 531);
        musicTracks.put("Diango's Little Helpers", 532);
        musicTracks.put("Roll the Bones", 533);
        musicTracks.put("Mind over Matter", 534);
        musicTracks.put("Golden Touch", 535);
        musicTracks.put("On Thin Ice", 536);
        musicTracks.put("Dogs of War", 537);
        musicTracks.put("Autumn in Bridgelum (Unlisted)", 538);
        musicTracks.put("Lucid Dream", 539);
        musicTracks.put("Scape Soft", 54);
        musicTracks.put("Oncoming Foe", 540);
        musicTracks.put("The Enchanter", 541);
        musicTracks.put("Lament", 542);
        musicTracks.put("The Dragon Slayer", 543);
        musicTracks.put("Making Waves", 544);
        musicTracks.put("Cabin Fever", 545);
        musicTracks.put("Last Stand", 546);
        musicTracks.put("Scape Santa", 547);
        musicTracks.put("Poles Apart", 548);
        musicTracks.put("Relics", 549);
        musicTracks.put("High Seas", 55);
        musicTracks.put("Mythical", 550);
        musicTracks.put("The Walking Dead", 551);
        musicTracks.put("Scape Five", 552);
        musicTracks.put("Museum Medley", 553);
        musicTracks.put("Roots and Flutes", 554);
        musicTracks.put("A Taste of Hope", 555);
        musicTracks.put("Welcome to the Theatre", 556);
        musicTracks.put("Bloodbath", 557);
        musicTracks.put("Food for Thought", 558);
        musicTracks.put("Malady", 559);
        musicTracks.put("Doorways", 56);
        musicTracks.put("Dance of Death", 560);
        musicTracks.put("Conspiracy (Old)", 561);
        musicTracks.put("Conspiracy", 561);
        musicTracks.put("Vanescula", 562);
        musicTracks.put("Bait", 563);
        musicTracks.put("Last King of the Yarasa", 564);
        musicTracks.put("Wrath and Ruin", 565);
        musicTracks.put("It's not over 'til...", 566);
        musicTracks.put("Predator Xarpus (2018)", 567);
        musicTracks.put("Predator Xarpus", 567);
        musicTracks.put("Storm Brew", 568);
        musicTracks.put("The Maiden's Anger", 569);
        musicTracks.put("Rune Essence", 57);
        musicTracks.put("The Maiden's Sorrow", 570);
        musicTracks.put("The Nightmare Continues", 571);
        musicTracks.put("The Fat Lady Sings", 572);
        musicTracks.put("The Mad Mole", 573);
        musicTracks.put("K'klik's Theme (Unlisted)", 574);
        musicTracks.put("Chickened Out", 575);
        musicTracks.put("Davy Jones' Locker", 576);
        musicTracks.put("Mastermindless", 577);
        musicTracks.put("Welcome to my Nightmare", 578);
        musicTracks.put("Arachnids of Vampyrium (2018)", 579);
        musicTracks.put("Arachnids of Vampyrium", 579);
        musicTracks.put("Nomad", 58);
        musicTracks.put("Dance of the Nylocas (2018)", 580);
        musicTracks.put("Dance of the Nylocas", 580);
        musicTracks.put("Power of the Shadow Realm", 581);
        musicTracks.put("The Curtain Closes", 582);
        musicTracks.put("Chef Surprise", 583);
        musicTracks.put("The Dark Beast Sotetseg", 584);
        musicTracks.put("Barren Land", 585);
        musicTracks.put("Everlasting Fire", 586);
        musicTracks.put("Null and Void", 587);
        musicTracks.put("Pest Control", 588);
        musicTracks.put("Snowflake & My Arm", 589);
        musicTracks.put("Cursed", 59);
        musicTracks.put("Lumbering", 590);
        musicTracks.put("Tomb Raider", 591);
        musicTracks.put("Troll Shuffle", 592);
        musicTracks.put("Mother Ruckus", 593);
        musicTracks.put("No Way Out", 594);
        musicTracks.put("Way of the Wyrm", 595);
        musicTracks.put("Creeping Vines", 596);
        musicTracks.put("Newbie Farming", 597);
        musicTracks.put("Alchemical Attack!", 598);
        musicTracks.put("Hoe Down", 599);
        musicTracks.put("Jolly R", 6);
        musicTracks.put("Lasting", 60);
        musicTracks.put("Method of Madness", 600);
        musicTracks.put("A Thorn in My Side", 601);
        musicTracks.put("Fear and Loathing", 602);
        musicTracks.put("Funny Bunnies", 603);
        musicTracks.put("Assault and Battery", 604);
        musicTracks.put("On the Frontline", 605);
        musicTracks.put("The Depths", 606);
        musicTracks.put("Stuck in the Mire", 607);
        musicTracks.put("Kanon of Kahlith", 608);
        musicTracks.put("A Farmer's Grind", 609);
        musicTracks.put("Village", 61);
        musicTracks.put("Distillery Hilarity", 610);
        musicTracks.put("Trouble Brewing", 611);
        musicTracks.put("Head to Head", 612);
        musicTracks.put("Grow Grow Grow", 613);
        musicTracks.put("Pinball Wizard", 614);
        musicTracks.put("Beetle Juice", 615);
        musicTracks.put("Back to Life", 616);
        musicTracks.put("Getting Down to Business", 617);
        musicTracks.put("Gill Bill", 618);
        musicTracks.put("Spy Games (Unlisted)", 619);
        musicTracks.put("Newbie Melody", 62);
        musicTracks.put("Where Eagles Lair", 620);
        musicTracks.put("Scape Home", 621);
        musicTracks.put("Waking Dream", 622);
        musicTracks.put("Dreamstate", 623);
        musicTracks.put("The Forsaken Tower", 624);
        musicTracks.put("The Lunar Isle", 625);
        musicTracks.put("Way of the Enchanter", 626);
        musicTracks.put("Isle of Everywhere", 627);
        musicTracks.put("Servants of Strife", 628);
        musicTracks.put("Burning Desire", 629);
        musicTracks.put("Chain of Command", 63);
        musicTracks.put("The Galleon", 630);
        musicTracks.put("Life's a Beach!", 631);
        musicTracks.put("Little Cave of Horrors", 632);
        musicTracks.put("On the Wing", 633);
        musicTracks.put("Warriors' Guild", 634);
        musicTracks.put("Ful to the Brim", 635);
        musicTracks.put("A Walk in the Woods", 636);
        musicTracks.put("Box of Delights", 637);
        musicTracks.put("H.A.M. Fisted", 638);
        musicTracks.put("A Forgotten Religion", 639);
        musicTracks.put("Book of Spells", 64);
        musicTracks.put("Sigmund's Showdown", 640);
        musicTracks.put("Sarachnis", 641);
        musicTracks.put("No Pasaran", 642);
        musicTracks.put("The Last Shanty", 643);
        musicTracks.put("Iorwerth's Lament", 644);
        musicTracks.put("Song of the Elves", 645);
        musicTracks.put("Night of the Vampyre", 646);
        musicTracks.put("Elven Guardians", 647);
        musicTracks.put("The Tower of Voices", 648);
        musicTracks.put("Trahaearn Toil", 649);
        musicTracks.put("Miracle Dance", 65);
        musicTracks.put("The Gauntlet", 650);
        musicTracks.put("Architects of Prifddinas", 651);
        musicTracks.put("The Fragment", 652);
        musicTracks.put("Faith of the Hefin", 653);
        musicTracks.put("Elven Seed", 654);
        musicTracks.put("Mystics of Nature", 655);
        musicTracks.put("Stand Up and Be Counted", 656);
        musicTracks.put("Sharp End of the Crystal", 657);
        musicTracks.put("The Fires of Lletya", 658);
        musicTracks.put("The Seed of Crwys", 659);
        musicTracks.put("Legion", 66);
        musicTracks.put("Dance of the Meilyr", 660);
        musicTracks.put("Close Quarters", 67);
        musicTracks.put("Cavern", 68);
        musicTracks.put("Egypt", 69);
        musicTracks.put("Overture", 7);
        musicTracks.put("Upcoming", 70);
        musicTracks.put("Chompy Hunt", 71);
        musicTracks.put("Fanfare", 72);
        musicTracks.put("All's Fairy in Love & War", 73);
        musicTracks.put("Lightwalk", 74);
        musicTracks.put("Venture", 75);
        musicTracks.put("Harmony", 76);
        musicTracks.put("Splendour", 77);
        musicTracks.put("Reggae", 78);
        musicTracks.put("The Desert", 79);
        musicTracks.put("Wildwood", 8);
        musicTracks.put("Soundscape", 80);
        musicTracks.put("Wonderous", 81);
        musicTracks.put("Waterfall", 82);
        musicTracks.put("Big Chords", 83);
        musicTracks.put("Dead Quiet", 84);
        musicTracks.put("Vision", 85);
        musicTracks.put("Dimension X", 86);
        musicTracks.put("Ice Melody", 87);
        musicTracks.put("Twilight", 88);
        musicTracks.put("Reggae 2", 89);
        musicTracks.put("Kingdom", 9);
        musicTracks.put("Ambient Jungle", 90);
        musicTracks.put("Riverside", 91);
        musicTracks.put("Sea Shanty", 92);
        musicTracks.put("Parade", 93);
        musicTracks.put("Tribal 2", 94);
        musicTracks.put("Intrepid", 95);
        musicTracks.put("Inspiration", 96);
        musicTracks.put("Hermit", 97);
        musicTracks.put("Forever", 98);
        musicTracks.put("Baroque", 99);
        musicTracks.put("Scape Crystal", 661);
        musicTracks.put("The Spurned Demon", 662);
        musicTracks.put("The Bane of Ashihama", 663);
        musicTracks.put("The Everlasting Slumber", 664);
        musicTracks.put("Lament for the Hallowed", 665);
        musicTracks.put("You Have My Attention", 666);
        musicTracks.put("The Terrible Caverns", 667);
        musicTracks.put("You Have My Attention (Part 2)", 668);
        musicTracks.put("Well Hallowed Air", 669);
        musicTracks.put("Arboretum", 670);
        musicTracks.put("Darkmeyer", 671);
        musicTracks.put("Upir Likhyi", 672);
        musicTracks.put("You Have My Attention (Part 1)", 673);
        musicTracks.put("Watch Your Step", 674);
        musicTracks.put("The Terrible Tunnels", 675);
        musicTracks.put("Morytanian Mystery", 676);
        musicTracks.put("Domain of the Vampyres", 677);
        musicTracks.put("Vampyre Assault", 678);
        musicTracks.put("Rest in Peace", 679);
        musicTracks.put("The Enclave", 680);
        musicTracks.put("Safety in Numbers", 681);
        musicTracks.put("Eve's Epinette", 682);
        musicTracks.put("Sea Minor Shanty", 683);
        musicTracks.put("A Dangerous Game", 684);
        musicTracks.put("Soul Wars", 685);
        musicTracks.put("The Waiting Game", 686);
        musicTracks.put("Scrubfoot's Descent", 687);
        musicTracks.put("Tempor of the Storm", 688);
        musicTracks.put("Barbarian Workout", 689);
        musicTracks.put("Race Against the Clock", 690);
        musicTracks.put("The Ruins of Camdozaal", 691);
        musicTracks.put("Rhapsody", 692);
        musicTracks.put("Clanliness", 693);
        musicTracks.put("Beneath the Kingdom", 694);
        musicTracks.put("Military Life", 695);
        musicTracks.put("Judgement of the Depths", 696);
        musicTracks.put("Regal Pomp", 697);
        musicTracks.put("The Part Where You Die", 698);
        musicTracks.put("The Houses of Kourend", 699);
        musicTracks.put("Rose", 700);
        musicTracks.put("Confrontation", 701);
        musicTracks.put("Itsy Bitsy...", 702);
        musicTracks.put("What Happens Below...", 703);
        musicTracks.put("Out at the Mines", 704);
        musicTracks.put("Not a Moment of Relief", 705);
        musicTracks.put("The Forests of Shayzien", 706);
        musicTracks.put("Beyond the Meadow", 707);
        musicTracks.put("A Festive Party", 708);
        musicTracks.put("The Ancient Prison", 709);
        musicTracks.put("Zaros Zeitgeist", 710);
        musicTracks.put("The Angel's Fury", 711);
    }
}
